namespace: ernstov
blank-refractor:
  defines: runnable
  containers:
    blank-refractor:
      build: .
  variables:
    password:
      env: ADMIN_PASSWORD
      type: string
      value: not-set
    user:
      env: ADMIN_USERNAME
      type: string
      value: admin
  services:
    webserver:
      container: blank-refractor
      port: 8080
      protocol: tcp
